name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    env:
      CODECOV_PACKAGE_NAME: DIContainer

    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: |
        set -o pipefail && swift test --no-parallel --enable-code-coverage | xcpretty -c;

    - name: Upload Code Coverage
      run: |
        bash <(curl -s https://codecov.io/bash) \
          -X xcodeplist \
          -J "$CODECOV_PACKAGE_NAME"
      env:
        CODECOV_TOKEN: bbf7a4f2-5199-4a17-b290-1ec9629b5390
